[package]
name = "bevy_fly_camera"
version = "0.10.0"
authors = ["aunyks", "mcpar-land"]
edition = "2021"
description = "A basic flying camera in Bevy"
license = "MIT"
repository = "https://github.com/aunyks/bevy_fly_camera"
readme = "README.md"

[dependencies]
bevy = { version = "^0.8.1" }
